apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fastapi-app
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: my-fastapi-app
  template:
    metadata:
      labels:
        app: my-fastapi-app
    spec:
      containers:
      - name: my-fastapi-app
        # image: kubernetes-test-app:latest
        # imagePullPolicy: Never  # Tell Kubernetes not to pull from a registry
        image: sri8096/my-fastapi-app:v1
        resources:
          limits:
            memory: "64Mi"
            cpu: "200m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: my-fastapi-app
spec:
  selector:
    app: my-fastapi-app
  ports:
  - port: 8080
    targetPort: 8000