name: DVC Pipeline CI

on: push

jobs:
  dvc-pipeline:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    # Checkout the repository to get access to your code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python (adjust the version to match your project)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install dependencies (make sure dvc is in your requirements.txt)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install DVC
    - name: Install DVC
      run: pip install dvc  # If not already in requirements.txt

    
    # Run the DVC pipeline (execute the pipeline using dvc repro)
    - name: dvc pipeline
      env:
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: dvc repro  # This will run the pipeline based on dvc.yaml

    - name: promote model to production
      if: success()
      env:
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: python scripts/production.py
   # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Build the Docker image
    - name: Build Docker Image
      if: ${{ success() }}
      run: |
        docker build -t sri8096/mushroom-predictor:latest .

    # Push the Docker image if the build was successful
    - name: Push Docker Image to DockerHub
      if: ${{ success() }}
      run: |
        docker push sri8096/mushroom-predictor:latest
